title: Settings
data:
  site_name: 'Marco Hyyryläinen'
  social:
    -
      name: Twitter
      url: 'https://twitter.com/wheresmarco'
      icon: site/social-icons/twitter.svg
    -
      name: Github
      url: 'https://github.com/wheresmarco'
      icon: site/social-icons/github.svg
    -
      name: Email
      url: 'mailto:marco@wheresmar.co'
      icon: site/social-icons/email.svg
